"""initial schema

Revision ID: c90a5fcc9b09
Revises: 
Create Date: 2026-05-08 14:36:27.289101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90a5fcc9b09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('vehicle_type', sa.Enum('BICYCLE', 'MOTORCYCLE', name='vehicle_type_enum'), nullable=False),
    sa.Column('vehicle_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('down_payment', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('financed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_payment', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_interest', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_to_pay', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('annual_interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_applications_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_applications_email'))

    op.drop_table('credit_applications')
    # ### end Alembic commands ###
